LAYOUT_OPTIONS = (
    (1, 'Vertical'),
    (2, 'Horizontal')
)

CARD = (
    (' ', 'clear'),
    ('card-primary', 'card-primary'),
    ('card-blue', 'card-blue'),
    ('card-indigo', 'card-indigo'),
    ('card-cyan', 'card-cyan'),
    ('card-danger', 'card-danger'),
    ('card-dark', 'card-dark'),
    ('card-fuchsia', 'card-fuchsia'),
    ('card-gray', 'card-gray'),
    ('card-gray-dark', 'card-gray-dark'),
    ('card-green', 'card-green'),
    ('card-info', 'card-info'),
    ('card-lime', 'card-lime'),
    ('card-maroon', 'card-maroon'),
    ('card-navy', 'card-navy'),
    ('card-olive', 'card-olive'),
    ('card-orange', 'card-orange'),
    ('card-outline', 'card-outline'),
    ('card-pink', 'card-pink'),
    ('card-purple', 'card-purple'),
    ('card-red', 'card-red'),
    ('card-secondary', 'card-secondary'),
    ('card-success', 'card-success'),
    ('card-teal', 'card-teal'),
    ('card-warning', 'card-warning'),
    ('card-white', 'card-white'),
    ('card-yellow', 'card-yellow'),
    ('card-outline card-primary', 'card-outline card-primary'),
    ('card-outline card-blue', 'card-outline card-blue'),
    ('card-outline card-indigo', 'card-outline card-indigo'),
    ('card-outline card-cyan', 'card-outline card-cyan'),
    ('card-outline card-danger', 'card-outline card-danger'),
    ('card-outline card-dark', 'card-outline card-dark'),
    ('card-outline card-fuchsia', 'card-outline card-fuchsia'),
    ('card-outline card-gray', 'card-outline card-gray'),
    ('card-outline card-gray-dark', 'card-outline card-gray-dark'),
    ('card-outline card-green', 'card-outline card-green'),
    ('card-outline card-info', 'card-outline card-info'),
    ('card-outline card-lime', 'card-outline card-lime'),
    ('card-outline card-maroon', 'card-outline card-maroon'),
    ('card-outline card-navy', 'card-outline card-navy'),
    ('card-outline card-olive', 'card-outline card-olive'),
    ('card-outline card-orange', 'card-outline card-orange'),
    ('card-outline card-outline', 'card-outline card-outline'),
    ('card-outline card-pink', 'card-outline card-pink'),
    ('card-outline card-purple', 'card-outline card-purple'),
    ('card-outline card-red', 'card-outline card-red'),
    ('card-outline card-secondary', 'card-outline card-secondary'),
    ('card-outline card-success', 'card-outline card-success'),
    ('card-outline card-teal', 'card-outline card-teal'),
    ('card-outline card-warning', 'card-outline card-warning'),
    ('card-outline card-white', 'card-outline card-white'),
    ('card-outline card-yellow', 'card-outline card-yellow'),
)

NAVBAR = (
    ('navbar-dark navbar-primary', 'navbar-primary'),
    ('navbar-dark navbar-secondary', 'navbar-secondary'),
    ('navbar-dark navbar-info', 'navbar-info'),
    ('navbar-dark navbar-success', 'navbar-success'),
    ('navbar-dark navbar-danger', 'navbar-danger'),
    ('navbar-dark navbar-indigo', 'navbar-indigo'),
    ('navbar-dark navbar-purple', 'navbar-purple'),
    ('navbar-dark navbar-pink', 'navbar-pink'),
    ('navbar-dark navbar-navy', 'navbar-navy'),
    ('navbar-dark navbar-lightblue', 'navbar-lightblue'),
    ('navbar-dark navbar-teal', 'navbar-teal'),
    ('navbar-dark navbar-cyan', 'navbar-cyan'),
    ('navbar-dark navbar-dark', 'navbar-dark'),
    ('navbar-dark navbar-gray-dark', 'navbar-gray-dark'),
    ('navbar-dark navbar-gray', 'navbar-gray'),
    ('navbar-light navbar-light', 'navbar-light'),
    ('navbar-light navbar-warning', 'navbar-warning'),
    ('navbar-light navbar-white', 'navbar-white'),
    ('navbar-light navbar-orange', 'navbar-orange'),
)

BRAND_LOGO = (
    (' ', 'clear'),
    ('navbar-primary', 'navbar-primary'),
    ('navbar-secondary', 'navbar-secondary'),
    ('navbar-info', 'navbar-info'),
    ('navbar-success', 'navbar-success'),
    ('navbar-danger', 'navbar-danger'),
    ('navbar-indigo', 'navbar-indigo'),
    ('navbar-purple', 'navbar-purple'),
    ('navbar-pink', 'navbar-pink'),
    ('navbar-navy', 'navbar-navy'),
    ('navbar-lightblue', 'navbar-lightblue'),
    ('navbar-teal', 'navbar-teal'),
    ('navbar-cyan', 'navbar-cyan'),
    ('navbar-dark', 'navbar-dark'),
    ('navbar-gray-dark', 'navbar-gray-dark'),
    ('navbar-gray', 'navbar-gray'),
    ('navbar-light', 'navbar-light'),
    ('navbar-warning', 'navbar-warning'),
    ('navbar-white', 'navbar-white'),
    ('navbar-orange', 'navbar-orange'),
)

SIDEBAR = (
    ('sidebar-dark-primary', 'sidebar-dark-primary'),
    ('sidebar-dark-warning', 'sidebar-dark-warning'),
    ('sidebar-dark-info', 'sidebar-dark-info'),
    ('sidebar-dark-danger', 'sidebar-dark-danger'),
    ('sidebar-dark-success', 'sidebar-dark-success'),
    ('sidebar-dark-indigo', 'sidebar-dark-indigo'),
    ('sidebar-dark-lightblue', 'sidebar-dark-lightblue'),
    ('sidebar-dark-navy', 'sidebar-dark-navy'),
    ('sidebar-dark-purple', 'sidebar-dark-purple'),
    ('sidebar-dark-fuchsia', 'sidebar-dark-fuchsia'),
    ('sidebar-dark-pink', 'sidebar-dark-pink'),
    ('sidebar-dark-maroon', 'sidebar-dark-maroon'),
    ('sidebar-dark-orange', 'sidebar-dark-orange'),
    ('sidebar-dark-lime', 'sidebar-dark-lime'),
    ('sidebar-dark-teal', 'sidebar-dark-teal'),
    ('sidebar-dark-olive', 'sidebar-dark-olive'),
    ('sidebar-light-primary', 'sidebar-light-primary'),
    ('sidebar-light-warning', 'sidebar-light-warning'),
    ('sidebar-light-info', 'sidebar-light-info'),
    ('sidebar-light-danger', 'sidebar-light-danger'),
    ('sidebar-light-success', 'sidebar-light-success'),
    ('sidebar-light-indigo', 'sidebar-light-indigo'),
    ('sidebar-light-lightblue', 'sidebar-light-lightblue'),
    ('sidebar-light-navy', 'sidebar-light-navy'),
    ('sidebar-light-purple', 'sidebar-light-purple'),
    ('sidebar-light-fuchsia', 'sidebar-light-fuchsia'),
    ('sidebar-light-pink', 'sidebar-light-pink'),
    ('sidebar-light-maroon', 'sidebar-light-maroon'),
    ('sidebar-light-orange', 'sidebar-light-orange'),
    ('sidebar-light-lime', 'sidebar-light-lime'),
    ('sidebar-light-teal', 'sidebar-light-teal'),
    ('sidebar-light-olive', 'sidebar-light-olive'),
)
