# Generated by Django 4.0.2 on 2022-10-23 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.purchase'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.provider', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='promotionsdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product'),
        ),
        migrations.AddField(
            model_name='promotionsdetail',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.promotions'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='paymentsdebtspay',
            name='debts_pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.debtspay', verbose_name='Cuenta por pagar'),
        ),
        migrations.AddField(
            model_name='paymentsctacollect',
            name='ctas_collect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.ctascollect', verbose_name='Cuenta por cobrar'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='type_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.typeexpense', verbose_name='Tipo de Gasto'),
        ),
        migrations.AddField(
            model_name='devolution',
            name='sale_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.saledetail'),
        ),
        migrations.AddField(
            model_name='debtspay',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.purchase'),
        ),
        migrations.AddField(
            model_name='ctascollect',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.sale'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
